name: Abode Camera Streaming
version: 1.2.9
slug: abode2rtc
description: Provides streaming video from Abode security cameras DVP
url: https://github.com/dvp-coms/hassio-addons/tree/main/abode2rtc
image: "ghcr.io/dvp-coms/{arch}-addon-abode2rtc"
arch: [amd64, aarch64, armv7, i386]
init: false
startup: services
host_network: true
homeassistant_api: true
video: false
audio: false
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: ["config:ro"]
ports:
  1984/tcp: 1984
  8554/tcp: 8554
  8555/tcp: 8555
  8555/udp: 8555
schema:
  abode_username: str
  abode_password: password
  locale: str
  debug: bool
options:
  abode_username: ""
  abode_password: ""
  locale: "en-US"
  debug: false
